### ISSUE TITLE
Post-migration changes

### ISSUE THREAD

**Issue by tobyhodges** [carpentries-incubator/workflows-snakemake#74]
Welcome to The Carpentries Incubator!

Now that the lesson has been transferred into the Incubator, a few things need to be updated on the repo (checking off the items I've taken care of already):

- [x] update URL to built pages
- [x] add topic tags needed to list the lesson the the [Community Developed Lessons](https://carpentries.org/community-lessons/) page: most of the topics I added ("lesson", "english" etc) are required for the lesson to be listed correctly but "snakemake" and "workflow-management" can be adjusted/removed as you prefer. Please check and add any extra tools or skills that are taught in the lesson.
- [x] update life cycle stage beta -> alpha: I'd recommend converting the lesson to use the [remote theme](https://github.com/carpentries/carpentries-theme) at the same time. I can prepare a PR for this, if that would help.
- [x] make the repository name more specific: I suspect we may get more lesson submissions relating to workflows, so I'd be in favour of giving this lesson repository a name like "workflows-snakemake" or similar. Let me know what you think.
- [x] arrange a follow-up video call so I can learn more about your plans for the lesson and how I and the rest of the Carpentries core team can support you: I'll contact you by email about this.

**Comment by DC23** [comment]
I think workflows-snakemake is a good idea. In a very early version of this, I had planned a two-part workshop. Part one would be building a workflow in Snakemake, and part two would be building the same workflow in Nextflow. Although I dropped that idea as being too much material for a single day, I didn't change the repo name.

**Comment by DC23** [comment]
I also think the following post-migration changes make sense:

- [ ] Remove all CSIRO-specific references
- [ ] Simplify or remove the installation instructions for Windows. The CSIRO Data School uses the Git Bash shell in combination with Anaconda on Windows quite frequently. But outside of this context I think this is quite a niche usage. I think the setup instructions should be made consistent with other Python-based Carpentry material. Perhaps I should make this a separate issue since it is a self-contained task that could benefit from further discussion.
- [ ] If possible, update the cluster execution section to be more generic. Probably just include generic instructions for SLURM and PBS systems, along with notes to contact your cluster support team if the instructions don't work correctly.

**Comment by tobyhodges** [comment]
the remote theme is addressed in #75.

when updating the lesson life cycle stage, you might also consider changing the lesson to use the Carpentries Incubator template (instead of the Software Carpentry template you're using now). This is done by changing `carpentry: swc` to `carpentry: incubator` in `_config.yml`.

if you're happy to change the repository slug to `workflows-snakemake`, please go ahead and do so. I'll watch out for that happening and then update the remote URL on my clone.

**Comment by DC23** [comment]
Thanks. The repo slug has been changed to workflows-snakemake. I will update the life cycle and templates soon.

**Comment by DC23** [comment]
I have broken out some of the larger tasks, so once I merge #75 and update the status/template this can be closed. It's the end of the day now, so I will tackle this tomorrow.
